// scripts/seedStaff.js
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const Staff = require('../model/staff.model');

// Staff data generator
const generateStaffData = () => {
    const basePassword = bcrypt.hashSync('Password123!', 10);
    const currentDate = new Date();
    const fiveYearsAgo = new Date(currentDate);
    fiveYearsAgo.setFullYear(currentDate.getFullYear() - 5);
    const tenYearsAgo = new Date(currentDate);
    tenYearsAgo.setFullYear(currentDate.getFullYear() - 10);

    return [
        // ─── PRINCIPAL ───────────────────────────────────────────────────────
        {
            staffId: 'STF-0001',
            serialNumber: 1,
            surname: 'Okafor',
            firstName: 'Chukwudi',
            middleName: 'Michael',
            gender: 'Male',
            dateOfBirth: new Date('1970-05-15'),
            maritalStatus: 'Married',
            religion: 'Christianity',
            nin: 'NGN123456789',
            nationality: 'Nigerian',
            stateOfOrigin: 'Anambra',
            localGovernment: 'Awka South',
            address: '15 Principal\'s Quarters, School Compound, Lagos',
            phone: '08012345678',
            alternativePhone: '08012345679',
            email: 'principal@school.edu.ng',
            emergencyContact: 'Mrs. Ada Okafor',
            emergencyPhone: '08012345680',
            emergencyRelation: 'Wife',
            staffType: 'principal',
            department: 'Administration',
            qualification: 'PhD Educational Management',
            specialization: 'School Leadership',
            dateOfEmployment: new Date('2010-09-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 500000,
            transportAllowance: 100000,
            housingAllowance: 200000,
            medicalAllowance: 50000,
            bankAccount: {
                bank: 'First Bank',
                accountNumber: '1000000001',
                accountName: 'Chukwudi M. Okafor'
            },
            pensionId: 'PEN001',
            taxId: 'TAX001',
            password: basePassword,
            mustResetPassword: false,
            photo: '/uploads/staff/principal.jpg',
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── VICE PRINCIPAL ACADEMIC ──────────────────────────────────────────
        {
            staffId: 'STF-0002',
            serialNumber: 2,
            surname: 'Eze',
            firstName: 'Ngozi',
            middleName: 'Florence',
            gender: 'Female',
            dateOfBirth: new Date('1975-03-22'),
            maritalStatus: 'Married',
            religion: 'Christianity',
            nin: 'NGN123456790',
            nationality: 'Nigerian',
            stateOfOrigin: 'Enugu',
            localGovernment: 'Enugu North',
            address: '23 Staff Quarters, School Compound, Lagos',
            phone: '08012345681',
            email: 'vp.academic@school.edu.ng',
            emergencyContact: 'Mr. Chidi Eze',
            emergencyPhone: '08012345682',
            emergencyRelation: 'Husband',
            staffType: 'vice_principal_academic',
            department: 'Academics',
            qualification: 'M.Ed Curriculum Studies',
            specialization: 'Curriculum Development',
            dateOfEmployment: new Date('2012-09-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 400000,
            transportAllowance: 80000,
            housingAllowance: 150000,
            medicalAllowance: 40000,
            bankAccount: {
                bank: 'GTBank',
                accountNumber: '1000000002',
                accountName: 'Ngozi F. Eze'
            },
            pensionId: 'PEN002',
            taxId: 'TAX002',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── VICE PRINCIPAL ADMINISTRATION ─────────────────────────────────────
        {
            staffId: 'STF-0003',
            serialNumber: 3,
            surname: 'Bello',
            firstName: 'Abdullahi',
            middleName: 'Ibrahim',
            gender: 'Male',
            dateOfBirth: new Date('1972-08-10'),
            maritalStatus: 'Married',
            religion: 'Islam',
            nin: 'NGN123456791',
            nationality: 'Nigerian',
            stateOfOrigin: 'Kaduna',
            localGovernment: 'Kaduna North',
            address: '45 Admin Block, School Compound, Lagos',
            phone: '08012345683',
            email: 'vp.admin@school.edu.ng',
            emergencyContact: 'Aisha Bello',
            emergencyPhone: '08012345684',
            emergencyRelation: 'Wife',
            staffType: 'vice_principal_admin',
            department: 'Administration',
            qualification: 'MBA Public Administration',
            specialization: 'School Administration',
            dateOfEmployment: new Date('2011-09-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 400000,
            transportAllowance: 80000,
            housingAllowance: 150000,
            medicalAllowance: 40000,
            bankAccount: {
                bank: 'Zenith Bank',
                accountNumber: '1000000003',
                accountName: 'Abdullahi I. Bello'
            },
            pensionId: 'PEN003',
            taxId: 'TAX003',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── HOD SCIENCE ──────────────────────────────────────────────────────
        {
            staffId: 'STF-0004',
            serialNumber: 4,
            surname: 'Adebayo',
            firstName: 'Oluwaseun',
            middleName: 'Peter',
            gender: 'Male',
            dateOfBirth: new Date('1980-11-28'),
            maritalStatus: 'Married',
            religion: 'Christianity',
            nin: 'NGN123456792',
            nationality: 'Nigerian',
            stateOfOrigin: 'Oyo',
            localGovernment: 'Ibadan North',
            address: '12 Science Block, School Compound, Lagos',
            phone: '08012345685',
            email: 'hod.science@school.edu.ng',
            emergencyContact: 'Mrs. Funke Adebayo',
            emergencyPhone: '08012345686',
            emergencyRelation: 'Wife',
            staffType: 'hod_science',
            department: 'Science',
            qualification: 'M.Sc Physics',
            specialization: 'Physics Education',
            dateOfEmployment: new Date('2013-09-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 350000,
            transportAllowance: 70000,
            housingAllowance: 120000,
            medicalAllowance: 35000,
            subjects: ['Physics', 'Further Mathematics'],
            assignedClass: 'SS 3A',
            bankAccount: {
                bank: 'UBA',
                accountNumber: '1000000004',
                accountName: 'Oluwaseun P. Adebayo'
            },
            pensionId: 'PEN004',
            taxId: 'TAX004',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── HOD ARTS ─────────────────────────────────────────────────────────
        {
            staffId: 'STF-0005',
            serialNumber: 5,
            surname: 'Okonkwo',
            firstName: 'Ifeanyi',
            middleName: 'Emmanuel',
            gender: 'Male',
            dateOfBirth: new Date('1978-09-15'),
            maritalStatus: 'Married',
            religion: 'Christianity',
            nin: 'NGN123456793',
            nationality: 'Nigerian',
            stateOfOrigin: 'Anambra',
            localGovernment: 'Onitsha North',
            address: '8 Arts Department, School Compound, Lagos',
            phone: '08012345687',
            email: 'hod.arts@school.edu.ng',
            emergencyContact: 'Chioma Okonkwo',
            emergencyPhone: '08012345688',
            emergencyRelation: 'Wife',
            staffType: 'hod_arts',
            department: 'Arts',
            qualification: 'MA English Literature',
            specialization: 'English Language',
            dateOfEmployment: new Date('2014-09-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 350000,
            transportAllowance: 70000,
            housingAllowance: 120000,
            medicalAllowance: 35000,
            subjects: ['English Language', 'Literature in English'],
            assignedClass: 'SS 2B',
            bankAccount: {
                bank: 'Access Bank',
                accountNumber: '1000000005',
                accountName: 'Ifeanyi E. Okonkwo'
            },
            pensionId: 'PEN005',
            taxId: 'TAX005',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── HOD COMMERCIAL ───────────────────────────────────────────────────
        {
            staffId: 'STF-0006',
            serialNumber: 6,
            surname: 'Afolabi',
            firstName: 'Grace',
            middleName: 'Oluwatosin',
            gender: 'Female',
            dateOfBirth: new Date('1982-04-20'),
            maritalStatus: 'Married',
            religion: 'Christianity',
            nin: 'NGN123456794',
            nationality: 'Nigerian',
            stateOfOrigin: 'Ogun',
            localGovernment: 'Abeokuta North',
            address: '3 Commercial Block, School Compound, Lagos',
            phone: '08012345689',
            email: 'hod.commercial@school.edu.ng',
            emergencyContact: 'Mr. Adewale Afolabi',
            emergencyPhone: '08012345690',
            emergencyRelation: 'Husband',
            staffType: 'hod_commercial',
            department: 'Commercial',
            qualification: 'M.Sc Accounting',
            specialization: 'Financial Accounting',
            dateOfEmployment: new Date('2015-09-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 350000,
            transportAllowance: 70000,
            housingAllowance: 120000,
            medicalAllowance: 35000,
            subjects: ['Accounting', 'Commerce', 'Economics'],
            assignedClass: 'SS 1A',
            bankAccount: {
                bank: 'Fidelity Bank',
                accountNumber: '1000000006',
                accountName: 'Grace O. Afolabi'
            },
            pensionId: 'PEN006',
            taxId: 'TAX006',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── TEACHER - MATHEMATICS ────────────────────────────────────────────
        {
            staffId: 'STF-0007',
            serialNumber: 7,
            surname: 'Okoro',
            firstName: 'Emeka',
            middleName: 'David',
            gender: 'Male',
            dateOfBirth: new Date('1985-12-03'),
            maritalStatus: 'Single',
            religion: 'Christianity',
            nin: 'NGN123456795',
            nationality: 'Nigerian',
            stateOfOrigin: 'Imo',
            localGovernment: 'Owerri Municipal',
            address: '25 Staff Quarters, School Compound, Lagos',
            phone: '08012345691',
            email: 'emeka.okoro@school.edu.ng',
            emergencyContact: 'Mrs. Ngozi Okoro',
            emergencyPhone: '08012345692',
            emergencyRelation: 'Mother',
            staffType: 'teacher',
            department: 'Science',
            qualification: 'B.Sc Mathematics',
            specialization: 'Mathematics Education',
            dateOfEmployment: new Date('2018-09-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 180000,
            transportAllowance: 50000,
            housingAllowance: 80000,
            medicalAllowance: 20000,
            subjects: ['Mathematics', 'Further Mathematics'],
            assignedClass: 'SS 3A',
            bankAccount: {
                bank: 'First Bank',
                accountNumber: '1000000007',
                accountName: 'Emeka D. Okoro'
            },
            pensionId: 'PEN007',
            taxId: 'TAX007',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── TEACHER - ENGLISH ────────────────────────────────────────────────
        {
            staffId: 'STF-0008',
            serialNumber: 8,
            surname: 'Adebisi',
            firstName: 'Folake',
            middleName: 'Esther',
            gender: 'Female',
            dateOfBirth: new Date('1988-07-18'),
            maritalStatus: 'Married',
            religion: 'Christianity',
            nin: 'NGN123456796',
            nationality: 'Nigerian',
            stateOfOrigin: 'Lagos',
            localGovernment: 'Ikeja',
            address: '14 Alausa Street, Ikeja, Lagos',
            phone: '08012345693',
            email: 'folake.adebisi@school.edu.ng',
            emergencyContact: 'Mr. Kunle Adebisi',
            emergencyPhone: '08012345694',
            emergencyRelation: 'Husband',
            staffType: 'teacher',
            department: 'Arts',
            qualification: 'BA English Language',
            specialization: 'English Literature',
            dateOfEmployment: new Date('2019-09-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 180000,
            transportAllowance: 50000,
            housingAllowance: 80000,
            medicalAllowance: 20000,
            subjects: ['English Language', 'Literature in English'],
            assignedClass: 'SS 2A',
            bankAccount: {
                bank: 'GTBank',
                accountNumber: '1000000008',
                accountName: 'Folake E. Adebisi'
            },
            pensionId: 'PEN008',
            taxId: 'TAX008',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── CLASS TEACHER - JSS 3A ───────────────────────────────────────────
        {
            staffId: 'STF-0009',
            serialNumber: 9,
            surname: 'Nwachukwu',
            firstName: 'Ogechi',
            middleName: 'Mary',
            gender: 'Female',
            dateOfBirth: new Date('1986-02-28'),
            maritalStatus: 'Single',
            religion: 'Christianity',
            nin: 'NGN123456797',
            nationality: 'Nigerian',
            stateOfOrigin: 'Abia',
            localGovernment: 'Umuahia North',
            address: '7 Teachers Quarters, School Compound, Lagos',
            phone: '08012345695',
            email: 'ogechi.nwachukwu@school.edu.ng',
            emergencyContact: 'Mr. James Nwachukwu',
            emergencyPhone: '08012345696',
            emergencyRelation: 'Brother',
            staffType: 'class_teacher',
            department: 'Basic Education',
            qualification: 'B.Ed Primary Education',
            specialization: 'Junior Secondary Education',
            dateOfEmployment: new Date('2017-09-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 200000,
            transportAllowance: 50000,
            housingAllowance: 85000,
            medicalAllowance: 25000,
            subjects: ['Basic Science', 'Basic Technology', 'Social Studies'],
            assignedClass: 'JSS 3A',
            bankAccount: {
                bank: 'Zenith Bank',
                accountNumber: '1000000009',
                accountName: 'Ogechi M. Nwachukwu'
            },
            pensionId: 'PEN009',
            taxId: 'TAX009',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── BURSAR ───────────────────────────────────────────────────────────
        {
            staffId: 'STF-0010',
            serialNumber: 10,
            surname: 'Okeke',
            firstName: 'Chinedu',
            middleName: 'Patrick',
            gender: 'Male',
            dateOfBirth: new Date('1975-11-12'),
            maritalStatus: 'Married',
            religion: 'Christianity',
            nin: 'NGN123456798',
            nationality: 'Nigerian',
            stateOfOrigin: 'Anambra',
            localGovernment: 'Idemili North',
            address: '10 Finance Office, School Compound, Lagos',
            phone: '08012345697',
            email: 'bursar@school.edu.ng',
            emergencyContact: 'Mrs. Nkechi Okeke',
            emergencyPhone: '08012345698',
            emergencyRelation: 'Wife',
            staffType: 'bursar',
            department: 'Finance',
            qualification: 'B.Sc Accounting, ACA',
            specialization: 'Financial Management',
            dateOfEmployment: new Date('2010-01-15'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 300000,
            transportAllowance: 70000,
            housingAllowance: 120000,
            medicalAllowance: 35000,
            bankAccount: {
                bank: 'UBA',
                accountNumber: '1000000010',
                accountName: 'Chinedu P. Okeke'
            },
            pensionId: 'PEN010',
            taxId: 'TAX010',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── SECRETARY ────────────────────────────────────────────────────────
        {
            staffId: 'STF-0011',
            serialNumber: 11,
            surname: 'Uzoma',
            firstName: 'Ada',
            middleName: 'Chiamaka',
            gender: 'Female',
            dateOfBirth: new Date('1990-09-05'),
            maritalStatus: 'Single',
            religion: 'Christianity',
            nin: 'NGN123456799',
            nationality: 'Nigerian',
            stateOfOrigin: 'Enugu',
            localGovernment: 'Nsukka',
            address: '5 Admin Office, School Compound, Lagos',
            phone: '08012345699',
            email: 'secretary@school.edu.ng',
            emergencyContact: 'Dr. Emeka Uzoma',
            emergencyPhone: '08012345700',
            emergencyRelation: 'Father',
            staffType: 'secretary',
            department: 'Administration',
            qualification: 'B.Sc Office Management',
            specialization: 'Administrative Support',
            dateOfEmployment: new Date('2019-02-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 150000,
            transportAllowance: 40000,
            housingAllowance: 70000,
            medicalAllowance: 20000,
            bankAccount: {
                bank: 'Access Bank',
                accountNumber: '1000000011',
                accountName: 'Ada C. Uzoma'
            },
            pensionId: 'PEN011',
            taxId: 'TAX011',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── LIBRARIAN ────────────────────────────────────────────────────────
        {
            staffId: 'STF-0012',
            serialNumber: 12,
            surname: 'Ogunleye',
            firstName: 'Tolulope',
            middleName: 'Samuel',
            gender: 'Male',
            dateOfBirth: new Date('1983-06-19'),
            maritalStatus: 'Married',
            religion: 'Christianity',
            nin: 'NGN123456800',
            nationality: 'Nigerian',
            stateOfOrigin: 'Ondo',
            localGovernment: 'Akure South',
            address: 'Library Complex, School Compound, Lagos',
            phone: '08012345701',
            email: 'librarian@school.edu.ng',
            emergencyContact: 'Mrs. Funmilayo Ogunleye',
            emergencyPhone: '08012345702',
            emergencyRelation: 'Wife',
            staffType: 'librarian',
            department: 'Library Services',
            qualification: 'MLS Library Science',
            specialization: 'School Librarianship',
            dateOfEmployment: new Date('2016-09-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 180000,
            transportAllowance: 45000,
            housingAllowance: 80000,
            medicalAllowance: 25000,
            bankAccount: {
                bank: 'First Bank',
                accountNumber: '1000000012',
                accountName: 'Tolulope S. Ogunleye'
            },
            pensionId: 'PEN012',
            taxId: 'TAX012',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── LAB TECHNICIAN ───────────────────────────────────────────────────
        {
            staffId: 'STF-0013',
            serialNumber: 13,
            surname: 'Ibrahim',
            firstName: 'Musa',
            middleName: 'Abdullahi',
            gender: 'Male',
            dateOfBirth: new Date('1992-02-14'),
            maritalStatus: 'Single',
            religion: 'Islam',
            nin: 'NGN123456801',
            nationality: 'Nigerian',
            stateOfOrigin: 'Kano',
            localGovernment: 'Nasarawa',
            address: 'Science Laboratory, School Compound, Lagos',
            phone: '08012345703',
            email: 'lab.technician@school.edu.ng',
            emergencyContact: 'Alhaji Ibrahim Musa',
            emergencyPhone: '08012345704',
            emergencyRelation: 'Father',
            staffType: 'lab_technician',
            department: 'Science',
            qualification: 'ND Laboratory Technology',
            specialization: 'Science Lab Management',
            dateOfEmployment: new Date('2020-09-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 120000,
            transportAllowance: 35000,
            housingAllowance: 60000,
            medicalAllowance: 15000,
            bankAccount: {
                bank: 'Jaiz Bank',
                accountNumber: '1000000013',
                accountName: 'Musa A. Ibrahim'
            },
            pensionId: 'PEN013',
            taxId: 'TAX013',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── ICT INSTRUCTOR ───────────────────────────────────────────────────
        {
            staffId: 'STF-0014',
            serialNumber: 14,
            surname: 'Adekunle',
            firstName: 'Oluwafemi',
            middleName: 'Joshua',
            gender: 'Male',
            dateOfBirth: new Date('1991-10-25'),
            maritalStatus: 'Single',
            religion: 'Christianity',
            nin: 'NGN123456802',
            nationality: 'Nigerian',
            stateOfOrigin: 'Ekiti',
            localGovernment: 'Ado Ekiti',
            address: 'ICT Center, School Compound, Lagos',
            phone: '08012345705',
            email: 'ict.instructor@school.edu.ng',
            emergencyContact: 'Mrs. Grace Adekunle',
            emergencyPhone: '08012345706',
            emergencyRelation: 'Mother',
            staffType: 'ict_instructor',
            department: 'ICT',
            qualification: 'B.Sc Computer Science',
            specialization: 'ICT Education',
            dateOfEmployment: new Date('2021-01-10'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 150000,
            transportAllowance: 40000,
            housingAllowance: 70000,
            medicalAllowance: 20000,
            subjects: ['Computer Science', 'ICT'],
            bankAccount: {
                bank: 'GTBank',
                accountNumber: '1000000014',
                accountName: 'Oluwafemi J. Adekunle'
            },
            pensionId: 'PEN014',
            taxId: 'TAX014',
            password: basePassword,
            mustResetPassword: true, // New staff needs to reset password
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── NURSE ────────────────────────────────────────────────────────────
        {
            staffId: 'STF-0015',
            serialNumber: 15,
            surname: 'Ekwueme',
            firstName: 'Chinwe',
            middleName: 'Patience',
            gender: 'Female',
            dateOfBirth: new Date('1989-12-08'),
            maritalStatus: 'Married',
            religion: 'Christianity',
            nin: 'NGN123456803',
            nationality: 'Nigerian',
            stateOfOrigin: 'Ebonyi',
            localGovernment: 'Abakaliki',
            address: 'Clinic, School Compound, Lagos',
            phone: '08012345707',
            email: 'nurse@school.edu.ng',
            emergencyContact: 'Mr. Emeka Ekwueme',
            emergencyPhone: '08012345708',
            emergencyRelation: 'Husband',
            staffType: 'nurse',
            department: 'Medical',
            qualification: 'RN, RM',
            specialization: 'School Health',
            dateOfEmployment: new Date('2018-03-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 140000,
            transportAllowance: 38000,
            housingAllowance: 65000,
            medicalAllowance: 18000,
            bankAccount: {
                bank: 'Fidelity Bank',
                accountNumber: '1000000015',
                accountName: 'Chinwe P. Ekwueme'
            },
            pensionId: 'PEN015',
            taxId: 'TAX015',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── COUNSELOR ────────────────────────────────────────────────────────
        {
            staffId: 'STF-0016',
            serialNumber: 16,
            surname: 'Olayemi',
            firstName: 'Adebimpe',
            middleName: 'Ruth',
            gender: 'Female',
            dateOfBirth: new Date('1984-04-17'),
            maritalStatus: 'Married',
            religion: 'Christianity',
            nin: 'NGN123456804',
            nationality: 'Nigerian',
            stateOfOrigin: 'Osun',
            localGovernment: 'Osogbo',
            address: 'Counseling Unit, School Compound, Lagos',
            phone: '08012345709',
            email: 'counselor@school.edu.ng',
            emergencyContact: 'Dr. Adekunle Olayemi',
            emergencyPhone: '08012345710',
            emergencyRelation: 'Husband',
            staffType: 'counselor',
            department: 'Student Services',
            qualification: 'M.Ed Guidance & Counseling',
            specialization: 'School Counseling',
            dateOfEmployment: new Date('2017-09-01'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 170000,
            transportAllowance: 45000,
            housingAllowance: 75000,
            medicalAllowance: 22000,
            bankAccount: {
                bank: 'Zenith Bank',
                accountNumber: '1000000016',
                accountName: 'Adebimpe R. Olayemi'
            },
            pensionId: 'PEN016',
            taxId: 'TAX016',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── BOARDING MASTER ──────────────────────────────────────────────────
        {
            staffId: 'STF-0017',
            serialNumber: 17,
            surname: 'Usman',
            firstName: 'Suleiman',
            middleName: 'Abubakar',
            gender: 'Male',
            dateOfBirth: new Date('1978-08-30'),
            maritalStatus: 'Married',
            religion: 'Islam',
            nin: 'NGN123456805',
            nationality: 'Nigerian',
            stateOfOrigin: 'Niger',
            localGovernment: 'Bida',
            address: 'Boys Hostel, School Compound, Lagos',
            phone: '08012345711',
            email: 'boarding.master@school.edu.ng',
            emergencyContact: 'Hauwa Usman',
            emergencyPhone: '08012345712',
            emergencyRelation: 'Wife',
            staffType: 'boarding_master',
            department: 'Boarding',
            qualification: 'B.Ed Educational Administration',
            specialization: 'Boarding Management',
            dateOfEmployment: new Date('2015-08-15'),
            employmentType: 'Full-time',
            status: 'Active',
            salary: 190000,
            transportAllowance: 48000,
            housingAllowance: 82000,
            medicalAllowance: 26000,
            bankAccount: {
                bank: 'Jaiz Bank',
                accountNumber: '1000000017',
                accountName: 'Suleiman A. Usman'
            },
            pensionId: 'PEN017',
            taxId: 'TAX017',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── SECURITY (Inactive - On Leave) ───────────────────────────────────
        {
            staffId: 'STF-0018',
            serialNumber: 18,
            surname: 'Okafor',
            firstName: 'Chukwuma',
            middleName: 'Benjamin',
            gender: 'Male',
            dateOfBirth: new Date('1980-01-20'),
            maritalStatus: 'Married',
            religion: 'Christianity',
            nin: 'NGN123456806',
            nationality: 'Nigerian',
            stateOfOrigin: 'Delta',
            localGovernment: 'Asaba',
            address: 'Security Post, School Compound, Lagos',
            phone: '08012345713',
            email: 'security@school.edu.ng',
            emergencyContact: 'Mrs. Nkechi Okafor',
            emergencyPhone: '08012345714',
            emergencyRelation: 'Wife',
            staffType: 'security',
            department: 'Security',
            qualification: 'SSCE',
            specialization: 'Security Operations',
            dateOfEmployment: new Date('2019-01-15'),
            employmentType: 'Full-time',
            status: 'On Leave',
            statusReason: 'Medical leave - recovering from surgery',
            returnDate: new Date('2025-04-15'),
            salary: 100000,
            transportAllowance: 30000,
            housingAllowance: 50000,
            medicalAllowance: 15000,
            bankAccount: {
                bank: 'First Bank',
                accountNumber: '1000000018',
                accountName: 'Chukwuma B. Okafor'
            },
            pensionId: 'PEN018',
            taxId: 'TAX018',
            password: basePassword,
            mustResetPassword: false,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── DRIVER (Contract) ────────────────────────────────────────────────
        {
            staffId: 'STF-0019',
            serialNumber: 19,
            surname: 'Aliu',
            firstName: 'Bashir',
            middleName: '',
            gender: 'Male',
            dateOfBirth: new Date('1985-03-12'),
            maritalStatus: 'Married',
            religion: 'Islam',
            nin: 'NGN123456807',
            nationality: 'Nigerian',
            stateOfOrigin: 'Kwara',
            localGovernment: 'Ilorin West',
            address: 'Transport Unit, School Compound, Lagos',
            phone: '08012345715',
            email: 'driver@school.edu.ng',
            emergencyContact: 'Aisha Aliu',
            emergencyPhone: '08012345716',
            emergencyRelation: 'Wife',
            staffType: 'driver',
            department: 'Transport',
            qualification: 'SSCE, Professional Driving License',
            specialization: 'School Bus Operation',
            dateOfEmployment: new Date('2022-01-10'),
            employmentType: 'Contract',
            status: 'Active',
            salary: 90000,
            transportAllowance: 25000,
            housingAllowance: 40000,
            medicalAllowance: 12000,
            bankAccount: {
                bank: 'Polaris Bank',
                accountNumber: '1000000019',
                accountName: 'Bashir Aliu'
            },
            pensionId: 'PEN019',
            taxId: 'TAX019',
            password: basePassword,
            mustResetPassword: true,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },

        // ─── COOK (Part-time) ─────────────────────────────────────────────────
        {
            staffId: 'STF-0020',
            serialNumber: 20,
            surname: 'Effiong',
            firstName: 'Margaret',
            middleName: 'Edet',
            gender: 'Female',
            dateOfBirth: new Date('1990-07-08'),
            maritalStatus: 'Single',
            religion: 'Christianity',
            nin: 'NGN123456808',
            nationality: 'Nigerian',
            stateOfOrigin: 'Akwa Ibom',
            localGovernment: 'Uyo',
            address: 'Kitchen, School Compound, Lagos',
            phone: '08012345717',
            email: 'cook@school.edu.ng',
            emergencyContact: 'Mr. Edet Effiong',
            emergencyPhone: '08012345718',
            emergencyRelation: 'Father',
            staffType: 'cook',
            department: 'Catering',
            qualification: 'Food Hygiene Certificate',
            specialization: 'School Catering',
            dateOfEmployment: new Date('2023-09-01'),
            employmentType: 'Part-time',
            status: 'Active',
            salary: 60000,
            transportAllowance: 15000,
            housingAllowance: 25000,
            medicalAllowance: 10000,
            bankAccount: {
                bank: 'Union Bank',
                accountNumber: '1000000020',
                accountName: 'Margaret E. Effiong'
            },
            pensionId: 'PEN020',
            taxId: 'TAX020',
            password: basePassword,
            mustResetPassword: true,
            createdBy: 'system',
            lastUpdatedBy: 'system'
        },
    ];
};

// Seed function
const seedStaff = async () => {
    try {
        // Connect to MongoDB
        // await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/school_management');
        console.log('Connected to MongoDB');

        // Clear existing staff data
        await Staff.deleteMany({});
        console.log('Cleared existing staff data');

        // Generate and insert seed data
        const staffData = generateStaffData();
        const insertedStaff = await Staff.insertMany(staffData);
        
        console.log(`✅ Successfully seeded ${insertedStaff.length} staff records`);
        
        // Log summary
        console.log('\n📊 Staff Summary:');
        console.log('================');
        const summary = staffData.reduce((acc, staff) => {
            acc[staff.staffType] = (acc[staff.staffType] || 0) + 1;
            return acc;
        }, {});
        
        Object.entries(summary).forEach(([type, count]) => {
            console.log(`${type}: ${count}`);
        });
        
        console.log('\n🔑 Default password for all staff: Password123!');
        console.log('⚠️  Users marked with mustResetPassword: true will need to change password on first login');
        
        // Close connection
        await mongoose.connection.close();
        console.log('\nDatabase connection closed');
        
    } catch (error) {
        console.error('❌ Error seeding staff data:', error);
        process.exit(1);
    }
};

// Run seed if called directly
if (require.main === module) {
    seedStaff();
}

module.exports = { seedStaff, generateStaffData };